"""empty message

Revision ID: 371db2543f35
Revises: b4237bcd9c55
Create Date: 2020-03-04 19:01:20.293396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '371db2543f35'
down_revision = 'b4237bcd9c55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journal_entry', 'tai_chi')
    op.drop_column('journal_entry', 'done')
    op.drop_column('journal_entry', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal_entry', sa.Column('title', sa.VARCHAR(length=140), nullable=True))
    op.add_column('journal_entry', sa.Column('done', sa.BOOLEAN(), nullable=True))
    op.add_column('journal_entry', sa.Column('tai_chi', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
