"""empty message

Revision ID: 5ec6ca985163
Revises: c0cf3f4be16e
Create Date: 2020-03-03 17:39:38.585645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ec6ca985163'
down_revision = 'c0cf3f4be16e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'journal_entry', ['date'])
    op.drop_column('journal_entry', 'title')
    op.drop_column('journal_entry', 'done')
    op.drop_column('journal_entry', 'tai_chi')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal_entry', sa.Column('tai_chi', sa.BOOLEAN(), nullable=True))
    op.add_column('journal_entry', sa.Column('done', sa.BOOLEAN(), nullable=True))
    op.add_column('journal_entry', sa.Column('title', sa.VARCHAR(length=140), nullable=True))
    op.drop_constraint(None, 'journal_entry', type_='unique')
    # ### end Alembic commands ###
