"""empty message

Revision ID: 65736fe2a73e
Revises: 31de40dd1b91
Create Date: 2020-03-04 18:58:16.694695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65736fe2a73e'
down_revision = '31de40dd1b91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journal_entry', 'title')
    op.drop_column('journal_entry', 'done')
    op.drop_column('journal_entry', 'tai_chi')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal_entry', sa.Column('tai_chi', sa.BOOLEAN(), nullable=True))
    op.add_column('journal_entry', sa.Column('done', sa.BOOLEAN(), nullable=True))
    op.add_column('journal_entry', sa.Column('title', sa.VARCHAR(length=140), nullable=True))
    # ### end Alembic commands ###
