"""empty message

Revision ID: 99da48ef6b06
Revises: b17b0ced6c3a
Create Date: 2020-03-05 11:35:02.046966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99da48ef6b06'
down_revision = 'b17b0ced6c3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journal_entry', 'title')
    op.drop_column('journal_entry', 'done')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal_entry', sa.Column('done', sa.BOOLEAN(), nullable=True))
    op.add_column('journal_entry', sa.Column('title', sa.VARCHAR(length=140), nullable=True))
    # ### end Alembic commands ###
