"""empty message

Revision ID: b854fc69dd71
Revises: f175eb21482c
Create Date: 2020-03-02 20:25:36.093063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b854fc69dd71'
down_revision = 'f175eb21482c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journal_entry', 'title')
    op.drop_column('journal_entry', 'done')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal_entry', sa.Column('done', sa.BOOLEAN(), nullable=True))
    op.add_column('journal_entry', sa.Column('title', sa.VARCHAR(length=140), nullable=True))
    # ### end Alembic commands ###
