"""empty message

Revision ID: c0cf3f4be16e
Revises: cbeca3c2f723
Create Date: 2020-03-03 13:43:26.164229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0cf3f4be16e'
down_revision = 'cbeca3c2f723'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal_entry', sa.Column('running', sa.Boolean(), nullable=True))
    op.drop_column('journal_entry', 'title')
    op.drop_column('journal_entry', 'tai_chi')
    op.drop_column('journal_entry', 'done')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal_entry', sa.Column('done', sa.BOOLEAN(), nullable=True))
    op.add_column('journal_entry', sa.Column('tai_chi', sa.BOOLEAN(), nullable=True))
    op.add_column('journal_entry', sa.Column('title', sa.VARCHAR(length=140), nullable=True))
    op.drop_column('journal_entry', 'running')
    # ### end Alembic commands ###
