"""empty message

Revision ID: ca0b330ae06c
Revises: ed21926e0704
Create Date: 2020-03-02 19:57:14.294580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca0b330ae06c'
down_revision = 'ed21926e0704'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal_entry', sa.Column('steps', sa.Integer(), nullable=True))
    op.drop_column('journal_entry', 'done')
    op.drop_column('journal_entry', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal_entry', sa.Column('title', sa.VARCHAR(length=140), nullable=True))
    op.add_column('journal_entry', sa.Column('done', sa.BOOLEAN(), nullable=True))
    op.drop_column('journal_entry', 'steps')
    # ### end Alembic commands ###
