"""empty message

Revision ID: cbeca3c2f723
Revises: 8bacbc296723
Create Date: 2020-03-03 13:27:54.967747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbeca3c2f723'
down_revision = '8bacbc296723'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal_entry', sa.Column('tai_chi', sa.Boolean(), nullable=True))
    op.add_column('journal_entry', sa.Column('yoga', sa.Boolean(), nullable=True))
    op.drop_column('journal_entry', 'title')
    op.drop_column('journal_entry', 'done')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal_entry', sa.Column('done', sa.BOOLEAN(), nullable=True))
    op.add_column('journal_entry', sa.Column('title', sa.VARCHAR(length=140), nullable=True))
    op.drop_column('journal_entry', 'yoga')
    op.drop_column('journal_entry', 'tai_chi')
    # ### end Alembic commands ###
